### PR TITLE
refactor sqs multi writer to use a worker group

### PR DESCRIPTION
**Pull request by jsteenb2**
refactors out the naive implementation of the worker group into a legit one

### CODE REVIEW

**Comment by jsteenb2** [comment]
going to push this upstream to original repo for inclusion there

**Comment by jsteenb2** [comment]
@jasonhancock have rebased and squashed a bunch of the bloated commit history, should be good to go now

**Comment by jsteenb2** [comment]
son of a billy block, my idea dir got added when I rebased -_-, will fix it up then push it back up

**Comment by jsteenb2** [comment]
@jasonhancock donezo with updates

**Comment by jasonhancock** [comment]
LGTM...ship it

**Pull request merged**
